### PR TITLE
test(es5): Add tests for `symbol` types

### PR DESCRIPTION
**Pull request by ExE-Boss**
This has been pointed out in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38947#discussion_r332063581.

### CODE REVIEW

**Comment by ljharb** [comment]
@ExE-Boss i'm somehow unable to force push to the PR branch on your fork despite "allow edits" being checked. Do you perhaps have branch protection set up, or created your fork in some atypical way?

**Comment by ExE-Boss** [comment]
Well, the fork is created on an organisation account (@EB-Forks) and not a personal account (@ExE-Boss).

**Comment by ljharb** [comment]
Hmm, I'd still expect if you have admin access on https://github.com/EB-Forks/ES-ToPrimitive that collabs on this PR would be given push access to it. Perhaps it's a github bug.

**Comment by ljharb** [comment]
Are you an org owner, or do you have explicit write/admin access on that repo?

**Comment by ExE-Boss** [comment]
I’m the owner of the @EB-Forks (and @EB-Tech) organisations.

---

I’ve added you as a collaborator to the forked repository, so you should be able to push to it now.

**Review by ljharb — APPROVED** [review]

**Pull request merged**
